### ISSUE TITLE
Problem with SingleChildScrollView

### ISSUE THREAD

**Issue by carmas123** [marcglasberg/align_positioned#1]
Hi and thank you for share you very good library with us...
I've a problem when use it with SingleChildScrollView.
I use SingleChildScrollView as child of AlignPositioned and the scrolling is not handled by SingleChildScrollView.

**Comment by marcglasberg** [comment]
Glad you like it. Regarding SingleChildScrollView not working, that's weird, and I'm not really sure what you mean. Can you share a minimum reproducible code (complete, with main etc)?

**Comment by carmas123** [comment]
I solved passing a child with fixed height into  SingleChildScrollView. Thank you.
This is my solution:

```
SingleChildScrollView(
  child: Container(
    height: 450,
    child: AlignPositioned(
      ...
    )
  )
)

```

**Comment by omidraha** [comment]
Thanks @carmas123.
