### ISSUE TITLE
Aligning Overflowed Children

### ISSUE THREAD

**Issue by hyun97** [marcglasberg/align_positioned#11]
https://stackoverflow.com/questions/72583553/flutter-aligning-overflowed-children
Can this library solve this problem?

Although dx and dw can be used to move the middle image of the 3x3 array to the middle of the parent container, it seems difficult to operate in a reactive manner on multiple devices.

Can the center image(2x2) always be centered in the parent widget in a reactive 3x3 array?

**Comment by marcglasberg** [comment]
I could not understand your question, sorry.

This library can position and size a child in relation to it's parent. If that's what you want to do, then yes. But you must be able to express the size/position of a child in terms of the size/position of the parent and the child itself.

Please, check carefully each parameter, as they cover all possible absolute and relative sizes and positions.
