### ISSUE TITLE
Switching pages will rebuild and cause the screen to flicker

### ISSUE THREAD

**Issue by itMcdull** [marcglasberg/align_positioned#4]
Switching pages will rebuild and cause the screen to flicker
The widget will move from the lower right corner to the set position
How to solve

**Comment by marcglasberg** [comment]
That's weird. Could you please provide me with some code I can run to see the problem? If you can show me some simple code to reproduce the problem I promise to tackle it right away.

**Comment by itMcdull** [comment]
Sorry, I have been too busy recently. I will provide you with sample code when I have time

**Comment by marcglasberg** [comment]
@itMcdull hey, still any chance you get the time to do this?

**Comment by itMcdull** [comment]
Sorry. I did not reproduce it in the demo. May be my problem

**Comment by marcglasberg** [comment]
Ok, I'm going to close this. Feel free to reopen if you have more info. Thanks.
