### ISSUE TITLE
[Feature Request] Add the `.expand()`constructor for the AnimatedAlignPositioned widget.

### ISSUE THREAD

**Issue by yasinarik** [marcglasberg/align_positioned#9]
Hi dear @marcglasberg . I hope you are doing great.

I've been a user of this package for a long time. I just forgot to say you that it is needed to add the`.expand()` constructor for the `AnimatedAlignPositioned` widget.

You already added it for the `AlignPositioned`. Currently, I am solving this issue by wrapping the widgets like this:

```dart
Stack(
  children: [
    Positioned(
      top: 0,
      right: 0,
      left: 0,
      bottom: 0,
        child: AnimatedAlignPositioned(
...
...
...
```

So the the `Positioned(top: 0, right: 0, left: 0, bottom: 0, child: child)` widget let the **AnimatedAlignPositioned** take the size of the parent **Stack** widget.

### Use Case
I have another widget inside the stack that basically shows an image pager whose height is determined by an AspectRatio. Since I use the AspectRatio widget, the non-positioned child of the stack (the image pager) has no height value. However, it can be laid out. So in such a case,  without the `.expand()` constructor, I have to use a `Positioned` widget. 

Not a big deal but it could be easier to implement. (Also there might be people that do not know how the stack widget works. Sometimes, even I forget to wrap it with the `Positioned(top: right: left: bottom: 0, child: child)` that makes me wonder "What I did wrong?" There can be a documentation update too.)

Thanks a lot!

**Comment by marcglasberg** [comment]
Could you please let me know if version [2.0.2] solves this issue? Thanks.

**Comment by yasinarik** [comment]
> Could you please let me know if version [2.0.2] solves this issue? Thanks.

Sorry for the late response. I was running version `align_positioned: ^2.0.1` and didn't know that you updated it. And yes, it solved the situation. Thanks again.

**Comment by yasinarik** [comment]
Oops, I think we are missing the **duration** and **curve** parameters while using `AnimatedAlignPositioned.expand()` constructor on version `align_positioned: ^2.0.2`. 

The regular `AnimatedAlignPositioned()` has them btw.

Am I right @marcglasberg ? It might require a quick fix.

**Comment by marcglasberg** [comment]
Fixed. Please see version 2.0.3. Thank you!
